
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvbzzlknglrrbudyckgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2Ynp6bGtuZ2xycmJ1ZHlja2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTU2ODUsImV4cCI6MjA1OTEzMTY4NX0.0XARDZyj-n3JX0jLlZf2m3gHLMJHDNk-1sjez99VgKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage,
  }
});
